// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCarCastro.Data;

#nullable disable

namespace RentCarCastro.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230706184443_Validation")]
    partial class Validation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RentCarCastro.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79f2df44-e8f4-421d-be4a-c6898520903a"),
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste.com",
                            IsActive = true,
                            Name = "Junior Castro",
                            Password = "admin@123"
                        },
                        new
                        {
                            Id = new Guid("d008051e-7546-48f3-bc3e-494e85fe981f"),
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste2.com",
                            IsActive = true,
                            Name = "José da Silva",
                            Password = "admin@123"
                        },
                        new
                        {
                            Id = new Guid("84a0e111-f838-4aa7-920e-2cbe3a2111b0"),
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste3.com",
                            IsActive = false,
                            Name = "Maria Cecília",
                            Password = "admin@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
