// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCarCastro.Data;

#nullable disable

namespace RentCarCastro.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20230711191006_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RentCarCastro.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 35063373,
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste.com",
                            IsActive = true,
                            Name = "Junior Castro",
                            Password = "admin@123",
                            UserName = "junior.castro"
                        },
                        new
                        {
                            Id = 2041960455,
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste2.com",
                            IsActive = true,
                            Name = "José da Silva",
                            Password = "admin@123",
                            UserName = "jose.silva"
                        },
                        new
                        {
                            Id = 942662159,
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste3.com",
                            IsActive = false,
                            Name = "Maria Cecília",
                            Password = "admin@123",
                            UserName = "maria.cecilia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
