// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentCarCastro.Data;

#nullable disable

namespace RentCarCastro.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RentCarCastro.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd1031dc-4db8-40cd-a679-9bac0ae276a5"),
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste.com",
                            IsActive = true,
                            Name = "Junior Castro",
                            Password = "admin@123"
                        },
                        new
                        {
                            Id = new Guid("041b9a79-e4b1-4e17-b864-506459f97cab"),
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste2.com",
                            IsActive = true,
                            Name = "José da Silva",
                            Password = "admin@123"
                        },
                        new
                        {
                            Id = new Guid("d7574dd4-8a18-4e48-9c73-80be10adc24f"),
                            CNPJ = "",
                            CPF = "27904525801",
                            Email = "teste@teste3.com",
                            IsActive = false,
                            Name = "Maria Cecília",
                            Password = "admin@123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
